services:
  - type: web
    name: asclepius-api
    env: python
    plan: free
    buildCommand: cd server && pip install -r requirements-deploy.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        value: 7842630384:AAGoSMjP0Eb_R_hJTGaUmxJmfAyiYsKRFpI
      - key: TELEGRAM_NURSE_CHAT_ID
        value: -5144644074
      - key: TELEGRAM_DOCTOR_CHAT_ID  
        value: -5294441613
      - key: DEBUG
        value: true
