import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { getPendingProtocols, approveProtocol } from "../lib/api";

function ProtocolModal({ protocol, onClose, onApprove }) {
  const [notes, setNotes] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const handleApprove = async () => {
    setSubmitting(true);
    try { await onApprove(protocol.id, notes); onClose(); }
    finally { setSubmitting(false); }
  };

  if (!protocol) return null;

  const sections = [
    { key: "immediate_actions",   label: "IMMEDIATE ACTIONS",      icon: "⚡", color: "#ff2d78" },
    { key: "antibiotic_suggestion",label: "ANTIBIOTIC PROTOCOL",   icon: "⬡", color: "#00f5d4" },
    { key: "rationale",           label: "CLINICAL RATIONALE",     icon: "◉", color: "#f59e0b" },
  ];

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-6"
        style={{ background: "rgba(3,5,10,0.9)", backdropFilter: "blur(8px)" }}
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.92, opacity: 0, y: 20 }}
          animate={{ scale: 1, opacity: 1, y: 0 }}
          exit={{ scale: 0.95, opacity: 0 }}
          transition={{ type: "spring", damping: 28, stiffness: 300 }}
          className="w-full max-w-2xl rounded-2xl overflow-hidden max-h-[88vh] overflow-y-auto"
          style={{ background: "#080c14", border: "1px solid rgba(255,45,120,0.2)" }}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header bar */}
          <div className="h-0.5" style={{ background: "linear-gradient(90deg, transparent, #ff2d78, #00f5d4, transparent)" }} />

          <div className="p-6">
            <div className="flex items-start justify-between mb-5">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-xs px-2 py-0.5 rounded-full" style={{ background: "rgba(255,45,120,0.1)", color: "#ff2d78", border: "1px solid rgba(255,45,120,0.2)" }}>
                    CRITICAL PROTOCOL #{protocol.id}
                  </span>
                  <span className="font-mono text-xs opacity-30">Score: {protocol.risk_score}/100</span>
                </div>
                <h2 className="font-display font-bold text-xl text-white">AI Treatment Protocol</h2>
                <p className="font-mono text-xs opacity-30 mt-0.5">Patient #{protocol.patient_id} · Generated by Gemini 2.0</p>
              </div>
              <button onClick={onClose} className="w-8 h-8 flex items-center justify-center rounded-lg font-mono text-sm opacity-30 hover:opacity-70 transition-opacity"
                style={{ background: "rgba(255,255,255,0.05)" }}>✕</button>
            </div>

            {/* Protocol sections */}
            <div className="flex flex-col gap-3 mb-5">
              {sections.map((s) => (
                protocol[s.key] && (
                  <div key={s.key} className="rounded-xl p-4" style={{ background: `${s.color}08`, border: `1px solid ${s.color}1a` }}>
                    <div className="flex items-center gap-2 mb-2">
                      <span style={{ color: s.color }}>{s.icon}</span>
                      <span className="font-mono text-xs tracking-widest" style={{ color: s.color, opacity: 0.7 }}>{s.label}</span>
                    </div>
                    <p className="font-mono text-xs text-white opacity-60 leading-relaxed whitespace-pre-line">{protocol[s.key]}</p>
                  </div>
                )
              ))}
            </div>

            {/* Doctor notes input */}
            <div className="mb-4">
              <label className="font-mono text-xs tracking-widest opacity-30 block mb-2">DOCTOR NOTES (optional)</label>
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Add clinical notes before approving..."
                rows={3}
                className="w-full rounded-xl px-4 py-3 font-mono text-xs resize-none outline-none transition-all"
                style={{
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.7)",
                }}
                onFocus={(e) => e.target.style.borderColor = "rgba(0,245,212,0.3)"}
                onBlur={(e) => e.target.style.borderColor = "rgba(255,255,255,0.08)"}
              />
            </div>

            {/* Action buttons */}
            <div className="flex gap-3">
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleApprove}
                disabled={submitting}
                className="flex-1 py-3 rounded-xl font-display font-bold text-sm tracking-widest uppercase transition-all"
                style={{
                  background: "linear-gradient(135deg, rgba(0,245,212,0.15), rgba(0,245,212,0.05))",
                  border: "1px solid rgba(0,245,212,0.3)",
                  color: "#00f5d4",
                  opacity: submitting ? 0.6 : 1,
                  boxShadow: "0 0 20px rgba(0,245,212,0.1)",
                }}
              >
                {submitting ? "APPROVING..." : "✓ APPROVE & NOTIFY NURSE"}
              </motion.button>
              <button onClick={onClose} className="px-5 py-3 rounded-xl font-mono text-xs opacity-30 hover:opacity-50 transition-opacity"
                style={{ border: "1px solid rgba(255,255,255,0.08)" }}>
                DEFER
              </button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

export default function ProtocolsPage() {
  const [protocols, setProtocols] = useState([]);
  const [selected, setSelected] = useState(null);
  const [isDark, setIsDark] = useState(true);

  useEffect(() => {
    const checkTheme = () => {
      setIsDark(document.body.classList.contains('light') === false);
    };
    checkTheme();
    const observer = new MutationObserver(checkTheme);
    observer.observe(document.body, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  const load = () => getPendingProtocols().then(setProtocols).catch(() => {});
  useEffect(() => { load(); const t = setInterval(load, 6000); return () => clearInterval(t); }, []);

  const handleApprove = async (id, notes) => {
    await approveProtocol(id, "Dr. System", notes);
    await load();
    setSelected(null);
  };

  return (
    <div className="min-h-screen grid-bg" style={{ paddingTop: "72px" }}>
      <div className="max-w-4xl mx-auto px-8 py-10">
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className={`font-display font-bold text-4xl ${isDark ? 'text-white' : 'text-gray-900'} mb-2`}>Protocol Review</h1>
              <p className={`font-mono text-xs ${isDark ? 'opacity-40' : 'opacity-60'} tracking-wide`}>GEMINI AI · RAG-POWERED · SURVIVING SEPSIS GUIDELINES</p>
            </div>
            <div className="flex items-center gap-2 px-4 py-2 rounded-xl" style={{ background: "rgba(255,45,120,0.1)", border: "1px solid rgba(255,45,120,0.25)" }}>
              <span className="relative flex h-2.5 w-2.5">
                {protocols.length > 0 && <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-pulse opacity-75" />}
                <span className="relative inline-flex rounded-full h-2.5 w-2.5" style={{ background: protocols.length > 0 ? "#ff2d78" : "#39ff14" }} />
              </span>
              <span className="font-mono text-xs font-semibold" style={{ color: protocols.length > 0 ? "#ff2d78" : "#39ff14" }}>
                {protocols.length} PENDING
              </span>
            </div>
          </div>
        </motion.div>

        {/* Gemini badge */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
          className="mb-8 rounded-xl px-6 py-4 flex items-center gap-4 hover:shadow-lg transition-all"
          style={{ background: "linear-gradient(135deg, rgba(0,245,212,0.08), rgba(56,189,248,0.08))", border: "1px solid rgba(0,245,212,0.15)" }}
        >
          <div className="w-10 h-10 rounded-lg flex items-center justify-center text-xl flex-shrink-0" style={{ background: "rgba(0,245,212,0.12)", border: "1px solid rgba(0,245,212,0.25)" }}>✦</div>
          <div>
            <p className="font-mono text-xs text-white opacity-70">Powered by <span style={{ color: "#00f5d4", fontWeight: "600" }}>Gemini 2.0 Flash Thinking</span> · RAG context: Surviving Sepsis Campaign 2021</p>
            <p className="font-mono text-xs opacity-30 mt-1">Patient allergies · Hospital antibiogram · Renal function · Comorbidities considered</p>
          </div>
        </motion.div>

        {/* Protocol cards */}
        <div className="flex flex-col gap-5">
          <AnimatePresence mode="popLayout">
            {protocols.length === 0 ? (
              <motion.div
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="text-center py-24 rounded-2xl"
                style={{ border: "1px dashed rgba(255,255,255,0.1)", background: "rgba(13,18,32,0.4)" }}
              >
                <div className="text-5xl mb-4 opacity-20">✦</div>
                <p className="font-mono text-xs tracking-widest opacity-30 mb-1">NO PENDING PROTOCOLS</p>
                <p className="font-mono text-xs opacity-20">Seed critical vitals to trigger AI protocol generation</p>
              </motion.div>
            ) : (
              protocols.map((p, i) => (
                <motion.div
                  key={p.id}
                  layout
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.96 }}
                  transition={{ delay: i * 0.06 }}
                  className="rounded-2xl p-6 cursor-pointer transition-all hover:shadow-lg"
                  style={{ background: "#0d1220", border: "1px solid rgba(255,45,120,0.15)", animation: "criticalBorder 2s ease-in-out infinite" }}
                  onClick={() => setSelected(p)}
                  whileHover={{ y: -2 }}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-3">
                        <span className="font-mono text-xs px-3 py-1 rounded-full font-semibold" style={{ background: "rgba(255,45,120,0.15)", color: "#ff2d78", border: "1px solid rgba(255,45,120,0.3)" }}>
                          PROTOCOL #{p.id}
                        </span>
                        <span className="font-mono text-xs opacity-40">Patient #{p.patient_id}</span>
                        <span className="font-mono text-xs opacity-40 ml-auto">{new Date(p.generated_at).toLocaleString()}</span>
                      </div>

                      <div className="font-display font-bold text-white mb-2">
                        Risk Score: <span style={{ color: "#ff2d78", textShadow: "0 0 20px #ff2d78", fontSize: "1.25em" }}>{p.risk_score}/100</span>
                      </div>

                      {p.immediate_actions && (
                        <p className="font-mono text-xs opacity-50 leading-relaxed line-clamp-2">{p.immediate_actions.split("\n")[0]}</p>
                      )}
                    </div>

                    <motion.div
                      whileHover={{ scale: 1.08 }}
                      className="ml-4 px-5 py-3 rounded-xl font-mono text-xs tracking-widest flex-shrink-0 font-semibold hover:shadow-lg transition-all"
                      style={{ background: "rgba(0,245,212,0.12)", border: "1px solid rgba(0,245,212,0.3)", color: "#00f5d4" }}
                    >
                      REVIEW →
                    </motion.div>
                  </div>
                </motion.div>
              ))
            )}
          </AnimatePresence>
        </div>
      </div>

      <ProtocolModal
        protocol={selected}
        onClose={() => setSelected(null)}
        onApprove={handleApprove}
      />
    </div>
  );
}
